### ISSUE TITLE
Boolean option is unclear

### ISSUE THREAD

**Issue by the-maldridge** [ConstellationApps/Forms#22]
On the rendered form, the boolean option is unclear if it is checked or not.  Perhaps this should be switched to an MDL checkbox?

**Comment by dinoocch** [comment]
Description should explain

**Comment by the-maldridge** [comment]
The MDL switch is a standardized UI element that is well understood.  This element is used widely in Android an iOS for boolean choices, if an end user is not familiar with the switch mechanism, the description should clear up any questions that exist.
